### PR TITLE
disable header preventing opening links to self

### LINKED ISSUE #109: Links to self (own domain) are blocked
## Steps to reproduce
1. Include a link to your PrivateBin in the bin editor or comment
2. Click on the link once sent or in preview

### What happens
Browser opens a new tab with a BLOCKED error (ERR_BLOCKED_BY_RESPONSE). 

### What should happen
Browser opens up a new tab with your PrivateBin page

## Additional information
This error occurs on both chrome and firefox.

A workaround for now is to middle click your PrivateBin links, then it works as expected.

Also, the link that is generated after posting works just fine... 

## Basic information
**Server address**: https://pastebin.tcloud.dev

**Server OS:** Ubuntu 20.04.3 LTS in a docker container ([cloudron](https://cloudron.io))

**Webserver:** nginx/1.18.0

**Browser:** All

**PrivateBin version:** 1.6.0

I can reproduce this issue on <https://privatebin.net>: Yes

Here is an example: https://privatebin.net/?8c0a4fe6d179f5a0#DmaksTnxDTYRwx3j2XjbP6uq4hWQjirTG1ZQwS5KZmUY
_**Will expire on Aug 12, 2022**_

### PR DESCRIPTION
**Pull request by elrido**
fixes #109 

Edit: updated issue ID, after moving that issue into the current project

### CODE REVIEW

File: etc/nginx/http.d/site.conf [hunk 1]
```diff
@@ -11,7 +11,10 @@ server {
         # https://developers.cloudflare.com/cache/about/cache-control#other
         add_header Cache-Control "public, max-age=3600, must-revalidate, no-transform";
         add_header Cross-Origin-Embedder-Policy require-corp;
-        add_header Cross-Origin-Opener-Policy same-origin;
+        # disabled, because it prevents links from a paste to the same site to
+        # be opened. Didn't work with `same-origin-allow-popups` either.
+        # See issue #959 for details.
```
Comment (rugk) [inline etc/nginx/http.d/site.conf:16]:
```suggestion
        # See issue #109 for details.
```

**Review by rugk — CHANGES_REQUESTED** [review]

**Review by rugk — APPROVED** [review]

**Comment by elrido** [comment]
Thank you!
